Update to new mango version 2.1.3
OFFIS-DAI/mango-library pull request #28
Opened 2024-12-19 15:43 UTC by emiliefro

- Use AgentAddress in respective Messages
- Update to new mango-agents version: creation of containers, agents and running scenarios

2024-12-19 16:16 UTC, rcschrg requested changes

2024-12-19 16:16 UTC, rcschrg commented on mango_library/coalition/core.py
>          :return: adress as tuple
update docstring

2024-12-19 16:16 UTC, rcschrg commented on mango_library/coalition/core.py
> +            participants: List[Tuple[ContainerAddress, str]],
Use AgentAddress

2024-12-19 16:16 UTC, rcschrg commented on mango_library/negotiation/cohda/cohda_negotiation.py
>                      for neighbor in coalition_assignment.neighbors:
Use AgentAddress List in CoalitionAssignment

2024-12-19 16:16 UTC, rcschrg commented on mango_library/negotiation/multiobjective_cohda/examples/simulation_util.py
> +        async with activate(container) as c:
You could also use add_agent_composed_of and move schedule actions to on_ready() lifecycle method

2024-12-19 16:16 UTC, rcschrg commented on mango_library/negotiation/termination.py
>      def on_send(
signature for on_send subscriptions is not content, receiver_addr: AgentAddress, **kwargs

2024-12-19 16:16 UTC, rcschrg commented on mango_library/negotiation/multiobjective_cohda/data_classes.py
> +import numpy
duplicate

2024-12-20 08:46 UTC, emiliefro commented on mango_library/coalition/core.py
>          for distance in range(1, k + 1):
efw

2024-12-20 08:47 UTC, emiliefro commented on mango_library/coalition/core.py
>          for part in accepted_participants:
ef

2024-12-20 08:48 UTC, emiliefro commented on mango_library/coalition/core.py
>          for part in accepted_participants:
x

2024-12-20 08:54 UTC, emiliefro commented on mango_library/coalition/core.py
>          for distance in range(1, k + 1):
f

2024-12-20 08:59 UTC, emiliefro commented on mango_library/coalition/core.py
>                  content=CoalitionAssignment(
h

2024-12-20 10:00 UTC, emiliefro commented on tests/unit_test/cohda/coalition_test.py
>  async def test_build_coalition(num_part):
lk

2025-01-02 12:20 UTC, merged